#MYSQL
#spring.application.name=BookStore
#spring.datasource.url=jdbc:mysql://localhost:3306/book_store?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
#spring.datasource.username=root
#spring.datasource.password=giaky113
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.data.web.pageable.serialization-mode=via-dto

#POSTSQL
#application.properties
#spring.datasource.url=jdbc:postgresql://localhost:5432/test
#spring.datasource.username=postgres
#spring.datasource.password=1
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d6lb6k7pm1nc7399h3h0-a/library_0i92}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:library_0i92_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:dcfifRTllzjd4oWc9XpkNQ82NtOyTuA1}
###
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true


# JPA / Hibernate 6 (Spring Boot 3.3.4)
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true


spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000



# JWT config
app.jwt.secret=DayLaChuoiSecretSieuCapVipProVoiHon32KyTu
app.jwt.expiration-ms=60000000 


spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=luugiaky100@gmail.com

spring.mail.password=kkto ggpz pfun qecd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false